### ISSUE TITLE
Unknown command line arguments are validated as part of "get_runnables"

### ISSUE THREAD

**Issue by ayalash** [getslash/slash#1006]
```
$ slash run -i --foo=bar
...
Traceback (most recent call last):
  File "/home/ayalas/src/github/slash/slash/frontend/slash_run.py", line 58, in slash_run
    collected = _collect_tests(app, args)
  File "/home/ayalas/src/github/slash/slash/frontend/slash_run.py", line 113, in _collect_tests
    collected = app.test_loader.get_runnables(paths, prepend_interactive=app.parsed_args.interactive)
  File "/home/ayalas/src/github/slash/slash/loader.py", line 57, in get_runnables
    sources = self._generate_repeats(self._generate_test_sources(paths))
  File "/home/ayalas/src/github/slash/slash/loader.py", line 82, in _generate_repeats
    for test in tests:
  File "/home/ayalas/src/github/slash/slash/loader.py", line 124, in <genexpr>
    return (t for t in iterator if matcher is None or matcher.matches(t.__slash__))
  File "/home/ayalas/src/github/slash/slash/loader.py", line 124, in <genexpr>
    return (t for t in iterator if matcher is None or matcher.matches(t.__slash__))
  File "/home/ayalas/src/github/slash/slash/loader.py", line 144, in _iter_test_address
    tests = list(self._iter_path(path))
  File "/home/ayalas/src/github/slash/slash/loader.py", line 182, in _iter_paths
    raise CannotLoadTests(msg)
```

The command line arguments are being verified as part of `Loader._iter_paths()`.

In the past, we recommended running projects with pre-defined tests as following:
```
def test_me():
    # Some pre-defined test
    pass

def main():
    tests = Loader().get_runnables(test_me)

    try:
        with app.session.get_started_context():
            run_tests(tests)
    except Exception as e:  #pylint: disable=broad-except
        _logger.error(str(e))
        return -1
    else:
        return 0
```
In this case, no command line verification will be done.

**Comment by ayalash** [comment]
@vmalloc I'm not sure what will be the best fix for that

**Comment by vmalloc** [comment]
Wouldn't skipping "paths" beginning with a dash be enough?

**Comment by ayalash** [comment]
If we skip them, then we should add the validation somewhere else - we don't want  to silently swallow unknown arguments.
Where is a better place for them, in your opinion?

**Comment by vmalloc** [comment]
Are we trying to fix only the use case above or are we trying to move the validation out of iter_paths for refactoring/aesthetics reasons? I'm not sure I'm following...

If the former is true, I think the use case makes sense and the users should make sure the "tests" being passed are actual test paths. If the latter is true, we can add a utility function in cli_utils or something similar to validate the command line being provided..

**Comment by ayalash** [comment]
I'm trying to fix the fact that the user doesn't receive error when it passes not-exist argument.
In current implementation, if I'll pass `--LL`, for example, slash will raise an exception because it doesn't know this test (although it is a flag).

I think that we should both add validation and do refactoring for aesthetics reasons.

I suggest that:
1. "iter_paths" should not handle strings which starts with `-` (dash) at all
2. The above code (of test_me) should add validation that no extra tests were passed
3. Add validation for non-exist flags which both regular "slash_run" and "test_me" code use for ensuring command line arguments.

What do you think?

**Comment by vmalloc** [comment]
Now that you put it that way I don't like that something receives an iterator that silently ignores things with dashes. It is better to raise an exception and have the user correct his or her code than to silently fail.

Otherwise it would mean that a slight typo (like the "-" being accidentally pressed when the user writes down the test path) would mean an entire test being ignored...
