### ISSUE TITLE
Slash swallow exceptions when set-attr is not not allowed

### ISSUE THREAD

**Issue by ayalash** [getslash/slash#1007]
Easy reproduction:
```
cat /tmp/testme.py 
class MyException(Exception):
    def __setattr__(self, *args):
        raise Exception('Set-attr')


def test_a():
    raise MyException('Ahhh')
```
```
$ slash run /tmp/testme.py
1 tests collected   
[2020-02-23 15:28:42] #1: /tmp/testme.py:test_a
E: <Error: Exception: Set-attr>, Test: </tmp/testme.py:test_a>
================================================================================================ Session Summary =================================================================================================
== #1: /tmp/testme.py:test_a =====================================================================================================================================================================================
 - Additional Details:
    > Log: '/tmp/logs/slash/2c82f6f8-5651-11ea-9485-d481d7207de7_0/2c82f6f8-5651-11ea-9485-d481d7207de7_0_1_debug.log'
 - 1/1 E (2020-02-23 17:28:42 +02:00):   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 /home/ayalas/virtualenvs/env3.6/bin/slash:10
>    sys.exit(main_entry_point())
 /home/ayalas/src/github/slash/slash/exception_handling.py:130
>        handle_exception(exc_info, **self._kwargs)
 /home/ayalas/src/github/slash/slash/exception_handling.py:151
>    already_handled = is_exception_handled(exc_value)
 /home/ayalas/src/github/slash/slash/exception_handling.py:175
>    return bool(get_exception_mark(e, "handled", False))
 /home/ayalas/src/github/slash/slash/utils/exception_mark.py:17
>    return _ensure_exception_marks(e).get(name, default)
 /home/ayalas/src/github/slash/slash/utils/exception_mark.py:28
>        setattr(e, _EXCEPTION_MARKS_NAME, returned)
 /tmp/testme.py:3
>        raise Exception('Set-attr')
E    Exception: Set-attr
============================================================ Session ended. 0 successful, 0 skipped, 0 failed, 1 erroneous. Total duration: 00:00:00 ============================================================
```

**Comment by ayalash** [comment]
Real-world reproduction:
```
Traceback (most recent call last):
  File "/Users/someone/proj/slash/slash/runner.py", line 113, in _run_single_test
    test.run()
  File "/Users/someone/proj/slash/slash/core/function_test.py", line 31, in run
    trigger_test_start=True, trigger_test_end=True,
  File "/Users/someone/proj/slash/slash/core/fixtures/fixture_store.py", line 61, in call_with_fixtures
    kwargs = self.get_fixture_dict(fixture_names, namespace)
  File "/Users/someone/proj/slash/slash/core/fixtures/fixture_store.py", line 274, in get_fixture_dict
    fixture = self.get_fixture_value(fixture, name=required_name)
  File "/Users/someone/proj/slash/slash/core/fixtures/fixture_store.py", line 282, in get_fixture_value
    value = self._compute_fixture_value(name, fixture)
  File "/Users/someone/proj/slash/slash/core/fixtures/fixture_store.py", line 336, in _compute_fixture_value
    reraise(*exc_info)
  File "/Users/someone/proj/slash/slash/utils/python.py", line 128, in reraise
    raise value
  File "/Users/someone/proj/slash/slash/core/fixtures/fixture_store.py", line 332, in _compute_fixture_value
    fixture_value = self._call_fixture(fixture, relative_name=relative_name)
  File "/Users/someone/proj/slash/slash/core/fixtures/fixture_store.py", line 384, in _call_fixture
    returned = active_fixture.value = fixture.get_value(kwargs, active_fixture)
  File "/Users/someone/proj/slash/slash/core/fixtures/fixture.py", line 70, in get_value
    return self.fixture_func(**kwargs)
  File "tests/test_vvol.py", line 14, in vvol_disk
    vvol_obj = create_vvol_disk(size=1000*MB)
    ...
  File "/Users/someone/env/lib/python3.7/site-packages/infi/pyvmomi_wrapper/client.py", line 59, in wait_for_task
    return self.wait_for_tasks([task], timeout)
  File "/Users/someone/env/lib/python3.7/site-packages/infi/pyvmomi_wrapper/client.py", line 56, in wait_for_tasks
    raise task.info.error
pyVmomi.VmomiSupport.vim.fault.InaccessibleDatastore: (vim.fault.InaccessibleDatastore) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = "Datastore 'ibox1283_default_vvol_ds' is not accessible. No connected and accessible host is attached to this datastore.",
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) [],
   datastore = 'vim.Datastore:datastore-242',
   name = 'ibox1283_default_vvol_ds',
   detail = 'notAccessible'
}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/someone/env/lib/python3.7/site-packages/pyVmomi/VmomiSupport.py", line 463, in GetPropertyInfo
    while name not in type._propInfo:
AttributeError: type object 'object' has no attribute '_propInfo'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/someone/env/bin/slash", line 10, in <module>
    sys.exit(main_entry_point())
  File "/Users/someone/proj/slash/slash/frontend/main.py", line 71, in main_entry_point
    sys.exit(main())
  File "/Users/someone/proj/slash/slash/frontend/main.py", line 47, in main
    returned = func(args.argv)
  File "/Users/someone/proj/slash/slash/frontend/slash_run.py", line 70, in slash_run
    run_tests(collected)
  File "/Users/someone/proj/slash/slash/runner.py", line 56, in run_tests
    _run_single_test(test, test_iterator)
  File "/Users/someone/proj/slash/slash/runner.py", line 113, in _run_single_test
    test.run()
  File "/Users/someone/proj/slash/slash/exception_handling.py", line 130, in __exit__
    handle_exception(exc_info, **self._kwargs)
  File "/Users/someone/proj/slash/slash/exception_handling.py", line 158, in handle_exception
    if is_exception_fatal(exc_value):
  File "/Users/someone/proj/slash/slash/exception_handling.py", line 225, in is_exception_fatal
    return bool(get_exception_mark(exception, "fatal", False))
  File "/Users/someone/proj/slash/slash/utils/exception_mark.py", line 17, in get_exception_mark
    return _ensure_exception_marks(e).get(name, default)
  File "/Users/someone/proj/slash/slash/utils/exception_mark.py", line 28, in _ensure_exception_marks
    setattr(e, _EXCEPTION_MARKS_NAME, returned)
  File "/Users/someone/env/lib/python3.7/site-packages/pyVmomi/VmomiSupport.py", line 664, in __setattr__
    CheckField(self._GetPropertyInfo(name), val)
  File "/Users/someone/env/lib/python3.7/site-packages/pyVmomi/VmomiSupport.py", line 469, in GetPropertyInfo
    raise AttributeError(name)
AttributeError: __slash_exc_marks__
```

**Comment by ayalash** [comment]
@vmalloc Any suggestions how to handle these cases?

**Comment by vmalloc** [comment]
So Slash does not swallow them - it just hides the real exception, right?

Won't this be solved by supporting chained exceptions?

**Comment by ayalash** [comment]
I think it is misleading that there is additional error due to the failure of setattr.

**Comment by vmalloc** [comment]
Maybe I'm not getting it properly - if there *was* an additional exception, it shouldn't be swallowed, no?

**Comment by yaelmi3** [comment]
Hey @vmalloc , @ayalash : Is there an update on this issue?

**Comment by ayalash** [comment]
@yaelmi3 I just push side branch `ayalas/issue-1007`.
Can you please run with it and check if it fixes the pyvmomi problem?

**Comment by yaelmi3** [comment]
@ayalash : works perfectly!

**Comment by ayalash** [comment]
Merged by PR https://github.com/getslash/slash/pull/1012
