### ISSUE TITLE
AttributeError occurs in parallel execution when exception issued on session_start or before_session_start

### ISSUE THREAD

**Issue by yaelmi3** [getslash/slash#1015]
```
import slash

class MyPlugin(slash.plugins.PluginInterface):
    def get_name(self):
        return 'bla'

    def session_start(self):
        raise ValueError

def test_bla():
    pass

slash.plugins.manager.install(MyPlugin(), activate=True)
```
Run test with --parallel

```
slash run tests/test_run.py --parallel=4
1 tests collected
Session error caught -- <Error: ValueError>

[2020-05-11 14:45:21] Unexpected error occurred
...
    raise ValueError
ValueError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/ymintz/slash/env/lib/python3.7/site-packages/slash/frontend/slash_run.py", line 64, in slash_run
    with app.session.get_started_context():
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/Users/ymintz/slash/env/lib/python3.7/site-packages/slash/core/session.py", line 144, in get_started_context
    self.reporter.report_session_end(self)
  File "/Users/ymintz/slash/env/lib/python3.7/site-packages/slash/reporting/console_reporter.py", line 207, in report_session_end
    if session.has_children() and session.parallel_manager.server.worker_error_reported:
AttributeError: 'NoneType' object has no attribute 'worker_error_reported'
ERROR: Unexpected error: 'NoneType' object has no attribute 'worker_error_reported'
```

**Comment by yaelmi3** [comment]
resolved in https://github.com/getslash/slash/pull/1017
