### ISSUE TITLE
Fixtuers does not work when using 'spawn' to create a process in Linux

### ISSUE THREAD

**Issue by eric1980** [getslash/slash#1016]
### Background
Python processes in Linux can be started using `fork` or `spawn`, as can be seen in the [python multiprocessing documentation](https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods). Default in Linux and MacOS is to use `fork`, while Windows uses `spawn`.

When using the default variant `fork` for process creation in Linux, the example found in the [slash documentation](https://slash.readthedocs.io/en/master/fixtures.html#fixture-scopes) (the background_process example) works fine, but when forcing Linux to use the `spawn` method, the test execution crash when the fixture calls `start()` on the process.
### Details
To use the example from the Slash documentation, we run the following file.

test_process.py
```python
from multiprocessing import Process, Event

import slash


# This fixture is taken from the slash documentation
@slash.fixture(scope='module')
def background_process(this):
    process = SomeComplexBackgroundProcess()

    @this.test_start
    def on_test_start():
        process.make_sure_still_running()

    @this.test_end
    def on_test_end():
        process.make_sure_no_errors()

    process.start()

    this.add_cleanup(process.stop)


# A class to implement required functionality from the fixture above
class SomeComplexBackgroundProcess(Process):
    def __init__(self):
        super().__init__()
        self.stop_signal = Event()

    def run(self):
        while not self.stop_signal.is_set():
            pass

    def stop(self):
        self.stop_signal.set()
        self.join()

    def make_sure_still_running(self):
        pass

    def make_sure_no_errors(self):
        pass


# Minimal test to utilise the fixture
def test_process(background_process):
    pass
```
The test runs fine, creates and stop the process inside the fixture. But, when adding the following lines to the top of the file to force the use of `spawn` when creating a process, it crashes.

added lines:
```python
import multiprocessing as mp
mp.set_start_method('spawn', force=True)
```

The somewhat cryptical error traceback looks like this:

```
test_process.py Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/<path-to-env>/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/<path-to-env>/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
ModuleNotFoundError: No module named '_0'
```

When creating a process the same way in plain Python without slash, it seems to work as expected. Is there something in the fixture implementation that prevent us from using `spawn` like we try to do here? The reason we need to use `spawn` is that we have other modules (pyVISA) that require processes to be spawned and not forked when using multiple processes. There are other reasons why we cannot use threads either in this case.

**Comment by vmalloc** [comment]
This could be an issue with `dessert`, not properly wiring the module path in `sys` to work properly in the new process. This requires further research to confirm/investigate unfortunately
