### ISSUE TITLE
Where is slash-script.py

### ISSUE THREAD

**Issue by nhershko** [getslash/slash#1029]
Hi,
I'm using slash and want to debug my solution (using vs-code).
So far I used slash-script.py as the entry point for debugger but it disappear on recent versions. 
Where can I find it? Is there another script entry point? 
Thanks,
N.

**Comment by vmalloc** [comment]
Not sure what slash-script.py is... You mean where is slash's entry point? It's usually started from `slash/frontend/main.py`...

**Comment by nhershko** [comment]
slash-script.py is file that appear inside python/scripts directory after installation with pip.
If it is something that you don't familiar with it might be related to pip - have no idea what generate it.
Anyway , I tried to run slash from tham main file and got the below error:

_Traceback (most recent call last):
  File "C:\Python37_64\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python37_64\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\Users\nhershko\.vscode\extensions\ms-python.python-2020.7.96456\pythonFiles\lib\python\debugpy\__main__.py", line 45, in <module>
    cli.main()
  File "c:\Users\nhershko\.vscode\extensions\ms-python.python-2020.7.96456\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 430, in main
    run()
  File "c:\Users\nhershko\.vscode\extensions\ms-python.python-2020.7.96456\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 267, in run_file
    runpy.run_path(options.target, run_name=compat.force_str("__main__"))
  File "C:\Python37_64\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Python37_64\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Python37_64\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:/Python36_64/Lib/site-packages/slash/frontend/main.py", line 7, in <module>
    import logbook # pylint: disable=F0401
ModuleNotFoundError: No module named 'logbook'_

**Comment by nhershko** [comment]
Here the file content. 
Is it generated by python? 

```
#!c:\python37\python.exe
# EASY-INSTALL-ENTRY-SCRIPT: 'slash==1.10.0','console_scripts','slash'
__requires__ = 'slash==1.10.0'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('slash==1.10.0', 'console_scripts', 'slash')()
    )

```

**Comment by vmalloc** [comment]
Oh this is Windows, yes... I think this is a hack being done by `pip`to create an executable for the `scripts`setup entry point...
