### ISSUE TITLE
Failures added with `slash.add_failure()` are not handled by xUnit properly.

### ISSUE THREAD

**Issue by sergei-dyshel** [getslash/slash#390]
In my test I use `slash.add_failure()` to add non-blocking failure. When xUnit is enabled (`--with-xunit`) this leads to a following error:
```
[2015-12-01 08:03:21] ERROR:slash.core.result: Failed to add error to result
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/slash/core/result.py", line 138, in _add_error
    hooks.error_added(result=self, error=error)  # pylint: disable=no-member
  File "/usr/lib/python2.7/site-packages/gossip/hooks.py", line 67, in __call__
    return self.trigger(kwargs)
  File "/usr/lib/python2.7/site-packages/gossip/hooks.py", line 152, in trigger
    break
  File "/usr/lib64/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/usr/lib/python2.7/site-packages/gossip/exception_policy.py", line 18, in context
    self._handle_trigger_end(ctx)
  File "/usr/lib/python2.7/site-packages/gossip/exception_policy.py", line 36, in _handle_trigger_end
    reraise(exc_type, exc_value, exc_tb)
  File "/usr/lib/python2.7/site-packages/gossip/hooks.py", line 159, in _call_registration
    registration(**kwargs)  # pylint: disable=star-args
  File "/usr/lib/python2.7/site-packages/gossip/registration.py", line 47, in __call__
    return self.func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/slash/plugins/builtin/xunit.py", line 47, in error_added
    self._add_error("error")
  File "/usr/lib/python2.7/site-packages/slash/plugins/builtin/xunit.py", line 52, in _add_error
    error_element = E(errortype, dict(type=exc_type.__name__, message=str(exc_value)))
AttributeError: 'NoneType' object has no attribute '__name__'
```

**Comment by vmalloc** [comment]
Will be released soon in 0.19.5
