### ISSUE TITLE
session crashes on traceback resolving exception

### ISSUE THREAD

**Issue by eplaut** [getslash/slash#483]
```
Traceback (most recent call last):
  File "/usr/local/bin/slash", line 11, in <module>
    load_entry_point('slash==1.0.2', 'console_scripts', 'slash')()
  File "/usr/local/lib/python2.7/dist-packages/slash/frontend/main.py", line 60, in main_entry_point
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/slash/frontend/main.py", line 43, in main
    return func(args.argv)
  File "/usr/local/lib/python2.7/dist-packages/slash/frontend/slash_run.py", line 39, in slash_run
    run_tests(collected)
  File "/usr/local/lib/python2.7/dist-packages/slash/runner.py", line 50, in run_tests
    _run_single_test(test, test_iterator)
  File "/usr/local/lib/python2.7/dist-packages/slash/runner.py", line 122, in _run_single_test
    raise
  File "/usr/local/lib/python2.7/dist-packages/slash/exception_handling.py", line 115, in __exit__
    handle_exception(exc_info, **self._kwargs)
  File "/usr/local/lib/python2.7/dist-packages/slash/exception_handling.py", line 145, in handle_exception
    handler(exc_info)
  File "/usr/local/lib/python2.7/dist-packages/slash/exception_handling.py", line 32, in update_current_result
    current_result.add_exception(exc_info)
  File "/usr/local/lib/python2.7/dist-packages/slash/core/result.py", line 63, in add_exception
    self.add_error(exc_info=exc_info)
  File "/usr/local/lib/python2.7/dist-packages/slash/core/result.py", line 131, in add_error
    err = self._add_error(self._errors, e, frame_correction=frame_correction + 1, exc_info=exc_info)
  File "/usr/local/lib/python2.7/dist-packages/slash/core/result.py", line 150, in _add_error
    error = Error.capture_exception(exc_info=exc_info)
  File "/usr/local/lib/python2.7/dist-packages/slash/core/error.py", line 58, in capture_exception
    returned = exc_value.__slash_captured_error__ = cls(exc_info=exc_info)
  File "/usr/local/lib/python2.7/dist-packages/slash/core/error.py", line 28, in __init__
    self.traceback = distill_traceback(tb, frame_correction=frame_correction)
  File "/usr/local/lib/python2.7/dist-packages/slash/utils/traceback_utils.py", line 29, in distill_traceback
    return _distill_frames(_get_tb_frames(tb), **kw)
  File "/usr/local/lib/python2.7/dist-packages/slash/utils/traceback_utils.py", line 47, in _distill_frames
    returned.frames.append(DistilledFrame(frame, lineno))
  File "/usr/local/lib/python2.7/dist-packages/slash/utils/traceback_utils.py", line 134, in __init__
    self.locals = self._capture_locals(frame)
  File "/usr/local/lib/python2.7/dist-packages/slash/utils/traceback_utils.py", line 169, in _capture_locals
    for key, value in frame.f_locals.items()
  File "/usr/local/lib/python2.7/dist-packages/slash/utils/traceback_utils.py", line 171, in <genexpr>
    for local_name, local_value in self._unwrap_local(key, value))
  File "/usr/local/lib/python2.7/dist-packages/slash/utils/traceback_utils.py", line 178, in _unwrap_local
    for attr in getattr(local_value, '__dict__', {}):
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/netref.py", line 150, in __getattr__
    return syncreq(self, consts.HANDLE_GETATTR, name)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/netref.py", line 71, in syncreq
    return conn.sync_request(handler, oid, *args)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 461, in sync_request
    self._send_request(seq, handler, args)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 254, in _send_request
    self._send(consts.MSG_REQUEST, seq, (handler, self._box(args)))
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 247, in _send
    self._channel.send(data)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/channel.py", line 69, in send
    self.stream.write(buf)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/stream.py", line 220, in write
    count = self.sock.send(data[:self.MAX_IO_CHUNK])
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/stream.py", line 82, in __getattr__
    raise EOFError("stream has been closed")
EOFError: stream has been closed
```

After this the session ends.

I know this is a edge case, but it is hard to face within the tests code.

Many thanks

**Comment by eplaut** [comment]
luckily it easy to simulate (using rpyc):
```
import rpyc

def test_01_a():
    conn = rpyc.classic.connect('localhost')
    conn.close()
    conn.modules.sys

def test_02_b():
    pass
```
need to start rpyc_classic server first

**Comment by vmalloc** [comment]
Sure, this is easy to fix. Pinning it to 1.1.0.

**Comment by eplaut** [comment]
Thanks! it works great!
