### ISSUE TITLE
AttributeError raised on report_session_end

### ISSUE THREAD

**Issue by ayalash** [getslash/slash#574]
```
$ slash run -SS tests -l logs --parallel $(nproc)
775 tests collected   
.....................................................................................................................s..s.ss.................................................................s...........................................................................s.s.....s........ss.....................ss..............................................ss..sss..ss...s......................s.........................s....s...........s.s..s.ssssssssssssssssss....................s..................................ss....s.............................................................ssss.ss..............................sss...............................................................................................................s..........................................[2017-06-06 13:13:39] Unexpected error occurred
Traceback (most recent call last):
  File "/builds/infradev/slash/slash/frontend/slash_run.py", line 61, in slash_run
    run_tests(collected)
  File "/usr/local/lib/python3.6/contextlib.py", line 89, in __exit__
    next(self.gen)
  File "/builds/infradev/slash/slash/core/session.py", line 123, in get_started_context
    self.reporter.report_session_end(self)
  File "/builds/infradev/slash/slash/reporting/console_reporter.py", line 177, in report_session_end
    self._report_result_warning_summary(session)
  File "/builds/infradev/slash/slash/reporting/console_reporter.py", line 221, in _report_result_warning_summary
    warnings_by_key.setdefault(warning.key, []).append(warning)
AttributeError: 'NoneType' object has no attribute 'key'
ERROR: Unexpected error: 'NoneType' object has no attribute 'key'
```

**Comment by maormarcus** [comment]
Fixed by commit 924feb589f311701feb67c0723133a57340c0293
