### ISSUE TITLE
Log cleanup: FileNotFoundError trying to remove highlights

### ISSUE THREAD

**Issue by drrlvn** [getslash/slash#750]
```
Traceback (most recent call last):
  File "/home/drorl/dev/slash/slash/frontend/slash_run.py", line 74, in slash_run
    app.set_exit_code(-1)
  File "/home/drorl/dev/slash/slash/app.py", line 153, in __exit__
    self._exit_stack.__exit__(exc_type, exc_value, exc_tb)
  File "/usr/lib/python3.6/contextlib.py", line 380, in __exit__
    raise exc_details[1]
  File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/drorl/dev/slash/slash/app.py", line 179, in _sigterm_context
    yield
  File "/usr/lib/python3.6/contextlib.py", line 365, in __exit__
    if cb(*exc_details):
  File "/usr/lib/python3.6/contextlib.py", line 284, in _exit_wrapper
    return cm_exit(cm, *exc_details)
  File "/home/drorl/dev/slash/slash/interfaces.py", line 10, in __exit__
    self.deactivate()
  File "/home/drorl/dev/slash/slash/core/session.py", line 91, in deactivate
    self._logging_context.__exit__(*exc_info) # pylint: disable=no-member
  File "/usr/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/home/drorl/dev/slash/slash/log.py", line 160, in get_session_logging_context
    yield path
  File "/usr/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/home/drorl/dev/slash/slash/log.py", line 188, in _get_file_logging_context
    yield handler, path
  File "/usr/lib/python3.6/contextlib.py", line 380, in __exit__
    raise exc_details[1]
  File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/drorl/dev/slash/slash/log.py", line 226, in _file_handler_cleanup_context
    yield handler
  File "/usr/lib/python3.6/contextlib.py", line 365, in __exit__
    if cb(*exc_details):
  File "/usr/lib/python3.6/contextlib.py", line 284, in _exit_wrapper
    return cm_exit(cm, *exc_details)
  File "/usr/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/home/drorl/dev/slash/slash/log.py", line 231, in _file_handler_cleanup_context
    os.remove(path)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/slash/3d06f992-1720-11e8-8bae-f48e3895dc21_0/highlights.log'
```

**Comment by vmalloc** [comment]
Should be fixed with the recent log refactoring pull requests
