### ISSUE TITLE
Session finished succesfully although no test run due to parallel manager error

### ISSUE THREAD

**Issue by ayalash** [getslash/slash#774]
From master session log:
```
[2018-04-02 18:14:47.839495] NOTICE:slash.parallel.server: All workers connected to server
[2018-04-02 18:14:53.689047] DEBUG:slash.parallel.server: Worker 2 validated tests successfully
[2018-04-02 18:14:55.001097] DEBUG:slash.parallel.server: Worker 1 validated tests successfully
[2018-04-02 18:14:55.002632] NOTICE:slash.parallel.server: All workers collected tests successfully, start serving tests
[2018-04-02 18:15:15.266636] ERROR:slash.parallel.parallel_manager: No request sent to server for 20 seconds, terminating
[2018-04-02 18:15:15.267977] ERROR:slash.parallel.parallel_manager: Clients that are still connected to server: dict_keys(['2', '1'])
[2018-04-02 18:15:15.268322] ERROR:slash.parallel.parallel_manager: Number of unstarted tests: 2057
[2018-04-02 18:15:15.268627] ERROR:slash.parallel.parallel_manager: Currently executed tests indexes: dict_values([None, None])
[2018-04-02 18:15:15.269952] ERROR:slash.parallel.parallel_manager: No worker error files were found
[2018-04-02 18:15:15.274053] TRACE:slash.parallel.server: Session finished. is_success=True has_skips=False
[2018-04-02 18:15:15.275344] DEBUG:slash.parallel.server: Exiting server loop
```

CI Link: http://ci.infinidat.com/view/Automation/view/Automation-Main/job/stability-nightly/label_exp=qa-regression-tests,system_type=real,tests_target=test_utils/26/console

**Comment by ayalash** [comment]
Both child sessions failed with:
```
[2018-04-02 18:15:04.971012] ERROR:slash.app: Unexpected error occurred                                                                                                                                            
Traceback (most recent call last):
  File "/stability-nightly/label_exp/qa-regression-tests/system_type/real/tests_target/test_utils/src/env/lib/python3.6/site-packages/slash/frontend/slash_run.py", line 61, in slash_run
    worker.start_execution(app, collected)
  File "/stability-nightly/label_exp/qa-regression-tests/system_type/real/tests_target/test_utils/src/env/lib/python3.6/site-packages/slash/parallel/worker.py", line 66, in start_execution
    tr.start()
  File "/usr/lib/python3.6/threading.py", line 846, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
```
